# This is a basic workflow to help you get started with Actions

name: B-C-2020-2

# Controls when the action will run. 
on:
  # Triggers the workflow on push or pull request events but only for the master branch
  push:
    branches: [ master ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-18.04

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2

      # Runs a single command using the runners shell
      - name: Install Node Js
        uses: actions/setup-node@v2-beta
        with:
          node-version: '12' 
        
      # Runs a set of commands using the runners shell
      - name: Install Yarn
        uses: Borales/actions-yarn@2.1.0
        with:
          run: install 

      # Runs a set of commands using the runners shell
      - name: Install Surge
        run: npm install -g surge

      # Runs a set of commands using the runners shell
      - name: Build With Yarn
        run: yarn build 
      
        
      # Runs a set of commands using the runners shell
      - name: Force To Autodeploy
        run: surge ./build http://b-c-2020-2.surge.sh --token ${{ secrets.SURGE_KEY }}
